<?php

//Multi page
define('__Retour', 'Retour au Menu de navigation');
define('__Reset', 'Annuler');
define('__Valide','Valider');
define('__Supprimer','Supprimer');
define('__Modifier','Modifier');

//Page tournoi:
define('__Titre_tournoi', 'Configuration du tournoi');
define('__Nom_tournoi', 'Nom du tournoi');
define('__Date_d', 'Date de debut');
define('__Date_f', 'Date fin');
define('__Type_t', 'Type de tournoi');
define('__Nbre_m', 'Nombre de manche');
define('__Nbre_to', 'Nombre de tour');
define('__Nbre_ta', 'Nombre de table');
define('__Table_t', 'Tournois enregistrés');
define('__Id_tournoi', 'Id tournoi');
define('__Id_configuration', 'Id_configuration');

//Page modification tournoi
define('__Titre_modif_tournoi', 'Modification du tournoi');

//Page tournoi, page configuration
define('__Choix_t', 'Choix du theme');

//Page configuraton
define('__Titre_configuration', 'Page thème');
define('__Ajout_t', 'Ajouter un nouveau thème');
define('__Table_co', 'Liste des thèmes');
define('__Id_co', 'Id thème');

//Poge modification configuration
define('__Titre_modif_configuration', 'Modification du des thèmes');


//Page parametre
define('__Titre_parametre', 'Ajout d\'un nouveau thème');
define('__Nom_p', 'Nom du thème');
define('__Cou_f', 'Couleur du Fond');
define('__Cou_t', 'Couleur du Texte');
define('__Taille', 'Taille de la police');
define('__Gras', 'Gras');
define('__Oui', 'Oui');
define('__Non', 'Non');
define('__Com_g', '0 pour NON, 1 pour OUI');
define('__Forme', 'Style de la police');
define('__Table_p', 'Parametres enregistrés');
define('__Id_parametre', 'Id parametre');

//Page de modification parametre
define('__Titre_modif_parametre', 'Modification des parametres');

//Page tableau: 
define('__Titre_tableau', 'Configuration du tableau');
define('__Nom_tableau', 'Nom du tableau');
define('__Descriptif', 'Descriptif du tableau');
define('__Id_tableau', 'Id tableau');
define('__Table_ta', 'Tableau enregistrés');

//Page modification tableau
define('__Titre_modif_tableau', 'Modification du tableau');

//Page tour:
define('__Titre_tour', 'Horaire des tours');
define('__Num_t', ' Tour');
define('__Horaire', 'Horaire du tour');
define('__Id_tour', 'Id tour');
define('__Table_to', 'Horaire enregistrés');

//Page modification tour
define('__Titre_modif_tour', 'Modification de l\`horaire');

//Page Rencontre:
define('__Titre_rencontre', 'Configuration des rencontres');
define('__Table', 'Numero de la table');
define('__Sel_Comp1', 'Seletion du Competiteur 1');
define('__Sel_Comp2', 'Selection du Competiteur 2');
define('__Comp1', 'Competiteur 1');
define('__Comp2', 'Competiteur 2');
define('__Id_match', 'Id match');
define('__Table_r', 'Matchs enregistrés');
define('__Statut', 'Statut');

//Page modification de la rencontre
define('__Titre_modif_match', 'Modification de la rencontre');

//Page Rencontre, Spnsor, Pub:
define('__Act', 'Action');
define('__Sup_i', 'Supprimer');
define('__Upload','Telecharger');

//Page Sponsor:
define('__Titre_sponsor', 'Configuration du sponsor');
define('__Liste_Sponsor', 'sponsor');
//Page Sponsor, Pub:
define('__Nom_f', 'Nom du fichier à telecharger');

define('__Image', 'Apercu du sponsor');
define('__Nom_i', 'Nom de l\'image');

//Page Pub:
define('__Titre_pub', 'Configuration des Publicitées');
define('__Titre_publicite', 'Liste des pubs');

//Page Menu
define('__Titre_menu', 'Menu de navigation');
define('__Tournoi', 'Configuration du tournoi');
define('__Tableau', 'Configuration du tableau');
define('__Tour', 'Configuration horaire des tours');
define('__Rencontre', 'Configuration des rencontres');
define('__Sponsor', 'Configuration du sponsor');
define('__Pub', 'Configuration des Pubs');
define('__Theme', 'Configuration du thème');
define('__Competiteur', 'Configuration des compétiteurs');
define('__Match', 'Partie score');
define('__aff_all', 'Affichage de toutes les tables ');
define('__aff_table', 'Affichage 1 table');


define('__Lien', 'Liens pour les differents affichage');


//Page competiteur
define('__Titre_competiteur', 'Ajout d\'un competiteur');
define('__Nom','Nom');
define('__Prenom','Prenom');
define('__Num_d','Numero du dossard');
define('__Sexe','Sexe');
define('__Cat_r','Catégorie réel du competiteur');
define('__Pays','Pays');
define('__BE','Belgique'); 
define('__BG','Bulgarie');
define('__CZ','République tchèque');
define('__DK','Danemark');
define('__DE','Allemagne');
define('__EE','Estonie');
define('__IE','Irlande');
define('__EL','Grèce');
define('__ES','Espagne');
define('__FR','France');
define('__HR','Croatie');
define('__IT','Italie');
define('__CY','Chypre');
define('__LV','Lettonie');
define('__LT','Lituanie');
define('__LU','Luxembourg');
define('__HU','Hongrie');
define('__MT','Malte');
define('__NL','Pays-Bas');
define('__AT','Autriche');
define('__PL','Pologne');
define('__PT','Portugal'); 
define('__RO','Roumanie');
define('__SI','Slovénie');
define('__SK','Slovaquie');
define('__FI','Finlande');
define('__SE','Suède');
define('__UK','Royaume-Uni');
define('__Rang','Rang');
define('__Sup_c','Page de suppression d\'un competiteur');
define('__Sup_r',' Supprimer');
define('__Table_c','Liste des competiteurs');
define('__Id_competiteur','Id competiteur');

// Page modification competiteur
define('__Titre_modif_competiteur', 'Modification du competiteur');


//Page supprime competiteur
define('__Titre_sup_c', 'Page de suppression d\'un competiteur');
define('__Sel_c','Selectionner le competiteur à supprimer ');

//Affichage des pubs
define('__Titre_Aff_p', 'Pub');

//Page match
define('__Titre_ma', 'Match ');
define('__Manche', 'Manche ');
define('__Faute', 'Faute ');
define('__Jaune', 'Carton Jaune');
define('__JR', 'Carton Jaune + Rouge (1)');
define('__JR2', 'Carton Jaune + Rouge (2)');
define('__WO', 'WO');
define('__TM', 'Temps Mort');
define('__Ret_se', 'Retour selection');
define('__Fin_m', 'Fin de match');
define('__Debut_m', 'Debut du match');


//accueil
define('__Utilisateur', 'Utilisateur');
define('__Paswword', 'Password');
define('__Titre_ac', 'Accueil');
//Page selection match admin
define('__Titre_se', 'Selection du match');
define('__Titre_mat', 'Choix du match');
define('__Retour_a', 'Retour a l\'accueil');
define('__Select', 'Selectionner');
define('__Table_sel_en_cour', 'Rencontre en cours');
define('__Table_sel_en_Att', 'Rencontre en attente');
define('__Table_sel_fin', 'Rencontre fini');
define('__Table_sel_enr', 'Rencontres enregistrées');
define('__Table_sel_archive', 'Rencontres archives');
define('__Action_att', 'En attente');
define('__Action_cours', 'En cours');
define('__Action_fin', 'Fini');
define('__Action_arch', 'Archive');


//menu _affichage
define('__Aff_tour', 'Score par poule');
define('__Aff_match', 'Score par match');
define('__Selection_match', 'Choix du match');
define('__Menu_affichage_', 'Menu');











